# -*- coding: utf-8 -*-
"""password.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10s6JiQy_oyUBtoH9U6P2A4XswN_qp9k7
"""

import streamlit as st
import string
import time

# 使える文字（英大小文字 + 数字 + 記号）
available_chars = string.ascii_letters + string.digits + string.punctuation

def simulate_brute_force(password):
    start_time = time.time()
    attempts = 0
    guessed_password = ''

    for char in password:
        for guess in available_chars:
            attempts += 1
            if guess == char:
                guessed_password += guess
                break

    end_time = time.time()
    elapsed_time = end_time - start_time

    # 危険度判定
    if elapsed_time < 0.01:
        danger = "\u975e\u5e38\u306b\u5371\u967a\uff08\u77ac\u6642\u306b\u89e3\u8aad\uff09"
    elif elapsed_time < 0.05:
        danger = "\u5371\u967a\uff08\u7c21\u5358\u306b\u89e3\u8aad\uff09"
    elif elapsed_time < 0.1:
        danger = "\u6ce8\u610f\uff08\u6570\u79d2\u3067\u89e3\u8aad\uff09"
    elif elapsed_time < 0.5:
        danger = "\u3084\u3084\u5b89\u5168\uff08\u3042\u308b\u7a0b\u5ea6\u6642\u9593\u304c\u304b\u304b\u308b\uff09"
    else:
        danger = "\u6bd4\u8f03\u7684\u5b89\u5168\uff08\u6642\u9593\u304c\u304b\u304b\u308b\uff09"

    return attempts, round(elapsed_time, 4), danger

st.title("\ud83d\udd10 ブルートフォース攻撃シミュレーター")
st.write("""
このツールでは、入力されたパスワードに対して、
ブルートフォース攻撃（総当たり）による解読を模擬体験できます。
""")

password = st.text_input("パスワードを入力してください（1〜10文字、英数字・記号OK）", type="password")

if password:
    if len(password) > 10:
        st.error("パスワードは10文字以内にしてください。")
    else:
        with st.spinner("解析中..."):
            attempts, elapsed, danger = simulate_brute_force(password)
        st.success("解析完了！")
        st.write(f"**入力されたパスワード：** {password}")
        st.write(f"**試行回数：** {attempts:,} 回")
        st.write(f"**解析時間：** {elapsed} 秒")
        st.write(f"**危険度：** {danger}")

        st.markdown("---")
        st.info("長くて複雑なパスワードほど、総当たり攻撃に強くなります。")